// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/PRI_CKT_block.v
// Created: 2026-01-29 17:23:39
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PRI_CKT_block
// Source Path: Testbench/PRI_CKT/PRI_CKT
// Hierarchy Level: 1
// Model version: 1.132
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PRI_CKT
          (u,
           y);


  input   [3:0] u;  // ufix4
  output  [3:0] y;  // ufix4


  reg [3:0] y_1;  // ufix4


  always @(u) begin
    if (u[3] != 1'b0) begin
      y_1 = 4'b1000;
    end
    else if (u[2] != 1'b0) begin
      y_1 = 4'b0100;
    end
    else if (u[1] != 1'b0) begin
      y_1 = 4'b0010;
    end
    else if (u[0] != 1'b0) begin
      y_1 = 4'b0001;
    end
    else begin
      y_1 = 4'b0000;
    end
  end

  assign y = y_1;

endmodule  // PRI_CKT_block

