// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/BCD_LUT.v
// Created: 2026-01-29 17:00:31
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BCD_LUT
// Source Path: Testbench/BCD_LUT
// Hierarchy Level: 0
// Model version: 1.125
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BCD_LUT
          (u,
           y);


  input   [1:0] u;  // ufix2
  output  [6:0] y;  // ufix7


  wire [6:0] Direct_Lookup_Table_n_D_1 [0:3];  // ufix7 [4]
  wire [6:0] Direct_Lookup_Table_n_D_out1;  // ufix7


  assign Direct_Lookup_Table_n_D_1[0] = 7'b1111110;
  assign Direct_Lookup_Table_n_D_1[1] = 7'b0110000;
  assign Direct_Lookup_Table_n_D_1[2] = 7'b1101101;
  assign Direct_Lookup_Table_n_D_1[3] = 7'b1111001;
  assign Direct_Lookup_Table_n_D_out1 = Direct_Lookup_Table_n_D_1[u];

  assign y = Direct_Lookup_Table_n_D_out1;

endmodule  // BCD_LUT

