// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/D_Flip_Flop.v
// Created: 2026-01-24 21:25:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: D_Flip_Flop
// Source Path: Testbench/D_Flip_Flop
// Hierarchy Level: 0
// Model version: 1.63
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module D_Flip_Flop
          (clk,
           reset,
           Q,
           D);


  input   clk;
  input   reset;
  input   [7:0] Q;  // uint8
  output  [7:0] D;  // uint8


  reg [7:0] Delay_out1;  // uint8


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        Delay_out1 <= Q;
      end
    end

  assign D = Delay_out1;

endmodule  // D_Flip_Flop

