// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/Adder.v
// Created: 2026-01-24 20:43:16
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Adder
// Source Path: Testbench/Adder
// Hierarchy Level: 0
// Model version: 1.50
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Adder
          (A,
           B,
           Sum);


  input   A;  // ufix1
  input   B;  // ufix1
  output  Sum;  // ufix1


  wire [1:0] Add_add_temp;  // ufix2
  wire [1:0] Add_1;  // ufix2
  wire [1:0] Add_2;  // ufix2
  wire Add_out1;  // ufix1


  assign Add_1 = {1'b0, A};
  assign Add_2 = {1'b0, B};
  assign Add_add_temp = Add_1 + Add_2;
  assign Add_out1 = Add_add_temp[0];

  assign Sum = Add_out1;

endmodule  // Adder

