// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/Bus_Inv.v
// Created: 2026-01-24 14:51:45
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Bus_Inv
// Source Path: Testbench/Bus_Inv
// Hierarchy Level: 0
// Model version: 1.9
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Bus_Inv
          (In1,
           Out1);


  input   [7:0] In1;  // uint8
  output  [7:0] Out1;  // uint8


  wire [7:0] Bitwise_NOT_out1;  // uint8


  assign Bitwise_NOT_out1 =  ~ In1;

  assign Out1 = Bitwise_NOT_out1;

endmodule  // Bus_Inv

