// -------------------------------------------------------------
// 
// File Name: hdlsrc/Testbench/SD_FSM_1001_block.v
// Created: 2026-02-03 10:44:39
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SD_FSM_1001_block
// Source Path: Testbench/SD_FSM_1001/SD_FSM_1001
// Hierarchy Level: 1
// Model version: 1.14
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SD_FSM_1001
          (clk,
           reset,
           x,
           y);

  // Default encoded enumeration values for type state_type_is_SD_FSM_1001
  parameter state_type_is_SD_FSM_1001_IN_S_1 = 3'd0, state_type_is_SD_FSM_1001_IN_S_10 = 3'd1, state_type_is_SD_FSM_1001_IN_S_100 = 3'd2, state_type_is_SD_FSM_1001_IN_S_1001 = 3'd3, state_type_is_SD_FSM_1001_IN_S = 3'd4;

  input   clk;
  input   reset;
  input   x;  // ufix1
  output  y;  // ufix1


  reg  y_1;  // ufix1
  reg [2:0] is_SD_FSM_1001;  // uint8
  reg [2:0] is_SD_FSM_1001_next;  // enum type state_type_is_SD_FSM_1001 (5 enums)


  always @(posedge clk or posedge reset)
    begin : SD_FSM_1001_process
      if (reset == 1'b1) begin
        is_SD_FSM_1001 <= state_type_is_SD_FSM_1001_IN_S;
      end
      else begin
        is_SD_FSM_1001 <= is_SD_FSM_1001_next;
      end
    end

  always @(is_SD_FSM_1001, x) begin
    is_SD_FSM_1001_next = is_SD_FSM_1001;
    case ( is_SD_FSM_1001)
      state_type_is_SD_FSM_1001_IN_S_1 :
        begin
          if (x == 1'b1) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_1;
          end
          else if (x == 1'b0) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_10;
          end
        end
      state_type_is_SD_FSM_1001_IN_S_10 :
        begin
          if (x == 1'b0) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_100;
          end
          else if (x == 1'b1) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_1;
          end
        end
      state_type_is_SD_FSM_1001_IN_S_100 :
        begin
          if (x == 1'b1) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_1001;
          end
          else if (x == 1'b0) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S;
          end
        end
      state_type_is_SD_FSM_1001_IN_S_1001 :
        begin
          if (x == 1'b0) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_10;
          end
          else if (x == 1'b1) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_1;
          end
        end
      default :
        begin
          //case IN_S__:
          if (x == 1'b0) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S;
          end
          else if (x == 1'b1) begin
            is_SD_FSM_1001_next = state_type_is_SD_FSM_1001_IN_S_1;
          end
        end
    endcase
  end

  always @(is_SD_FSM_1001) begin
    case ( is_SD_FSM_1001)
      state_type_is_SD_FSM_1001_IN_S_1 :
        begin
          y_1 = 1'b0;
        end
      state_type_is_SD_FSM_1001_IN_S_10 :
        begin
          y_1 = 1'b0;
        end
      state_type_is_SD_FSM_1001_IN_S_100 :
        begin
          y_1 = 1'b0;
        end
      state_type_is_SD_FSM_1001_IN_S_1001 :
        begin
          y_1 = 1'b1;
        end
      default :
        begin
          //case IN_S__:
          y_1 = 1'b0;
        end
    endcase
  end

  assign y = y_1;

endmodule  // SD_FSM_1001_block

